"use client";

import React, { useEffect, useState } from "react";
import { useVendingStore } from "@/lib/store";
import { vendingAPI } from "@/lib/api";
import { paymentService, PaymentRequest } from "@/lib/payment";
import { PaymentQR } from "@/components/PaymentQR";
import { Loading } from "@/components/ui/Loading";
import { Button } from "@/components/ui/Button";
import {
  ArrowLeft,
  CreditCard,
  QrCode,
  Wallet,
  ShoppingBag,
  ShieldCheck,
} from "lucide-react";
import toast from "react-hot-toast";
import Image from "next/image";

const PaymentScreen: React.FC = () => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState<
    "qris" | "midtrans" | null
  >(null);
  const [paymentToken, setPaymentToken] = useState<string | null>(null);

  const {
    currentOrder,
    selectedProduct,
    // cartItems,
    setCurrentScreen,
    resetTransaction,
    setLoading,
    setError,
  } = useVendingStore();

  // Load Snap.js script on component mount
  useEffect(() => {
    paymentService.loadSnapScript().catch((error) => {
      console.error("Failed to load Snap.js:", error);
    });
  }, []);

  useEffect(() => {
    if (!currentOrder || !selectedProduct) {
      setCurrentScreen("home");
    }
  }, [currentOrder, selectedProduct, setCurrentScreen]);

  if (!currentOrder || !selectedProduct) {
    return <Loading message="Memuat pembayaran..." fullScreen />;
  }

  // Handle Midtrans payment
  const handleMidtransPayment = async () => {
    if (!currentOrder) return;

    setIsProcessing(true);
    let paymentCompleted = false; // Track if payment completed successfully

    try {
      let token = paymentToken;

        if (!token) {
          console.log("⚠️ No payment token found, attempting to retrieve from backend...");
          
          try {
            // 1. Try to get latest order status from backend (might have token)
            const orderStatus = await vendingAPI.getOrderStatus(currentOrder.order_id);
            if (orderStatus.payment_token) {
              token = orderStatus.payment_token;
              console.log("✅ Token retrieved from order status");
            } else {
              // 2. If no token, ask backend to generate one by explicitly setting method to midtrans again
              console.log("🔄 Requesting new token from backend...");
              const updateResponse = await vendingAPI.updatePaymentMethod(
                currentOrder.order_id,
                "midtrans"
              );
              
              if (updateResponse.payment_token) {
                token = updateResponse.payment_token;
                console.log("✅ New token generated by backend");
              } else {
                throw new Error("Backend failed to return payment token");
              }
            }
            
            setPaymentToken(token);
          } catch (backendError) {
             console.error("❌ Failed to retrieve token from backend:", backendError);
             throw new Error("Gagal mendapatkan token pembayaran dari server. Silakan coba lagi.");
          }
        } else {
          console.log("♻️ Reusing existing payment token");
        }

      // Open Snap payment popup
      const result = await paymentService.openSnapPayment(token);

      console.log(
        "📊 Payment result received:",
        JSON.stringify(result, null, 2)
      );
      console.log("📊 Transaction status:", result.transaction_status);
      console.log("📊 Status code:", result.status_code);

      // Handle payment result
      if (
        result.transaction_status === "settlement" ||
        result.transaction_status === "capture"
      ) {
        console.log(
          "✅ Payment successful (settlement/capture), proceeding to dispense..."
        );
        paymentCompleted = true; // Mark as completed
        await handlePaymentSuccess();
      } else if (result.transaction_status === "pending") {
        // For VA/Bank Transfer - payment instructions shown
        console.log(
          "⏳ Payment pending (VA/Bank Transfer) - instructions shown to user"
        );
        paymentCompleted = true; // Mark as completed (pending is valid)

        // Verify payment (will update order status to PAID in pending state)
        try {
          await vendingAPI.verifyPayment(currentOrder.order_id, "SUCCESS");
          console.log("✅ Payment verified as pending");
        } catch (error) {
          console.error("❌ Failed to verify pending payment:", error);
        }

        // Show message explaining the payment is pending
        toast.success(
          "Instruksi pembayaran telah ditampilkan. Selesaikan pembayaran untuk mendapatkan produk."
        );

        // Go to dispensing screen with pending state
        setCurrentScreen("dispensing");
      } else {
        // Unknown status - log and stay on payment screen
        console.log("⚠️ Unknown payment status:", result.transaction_status);
        console.log("⚠️ Full result:", JSON.stringify(result, null, 2));

        // TEMPORARY: Assume success for any non-error status
        console.log("🔧 TEMP: Treating as success anyway...");
        paymentCompleted = true;
        await handlePaymentSuccess();
      }
    } catch (error) {
      console.error("❌ Midtrans payment error:", error);

      // Check if it's order_id duplicate error
      const errorMessage =
        error instanceof Error ? error.message : String(error);

      if (errorMessage.includes("order_id not unique")) {
        toast.error("Order ID sudah digunakan. Membuat pesanan baru...");
        // Reset and go back to create new order
        setTimeout(() => {
          resetTransaction();
          setPaymentToken(null);
          setCurrentScreen("home");
        }, 2000);
      } else if (!errorMessage.includes("closed")) {
        // Real error - show error message
        toast.error("Pembayaran gagal. Silakan coba lagi.");
      } else if (!paymentCompleted) {
        // User closed popup BEFORE payment completed
        console.log("🚪 User closed payment popup before completing payment");
        setPaymentMethod(null); // Reset payment method to show selection again
        setPaymentToken(null); // Clear token so new transaction can be created
      } else {
        // Payment already completed, popup just closed - do nothing
        console.log("✅ Payment completed, popup closed normally - ignoring");
      }
    } finally {
      setIsProcessing(false);
    }
  };

  const handlePaymentSuccess = async () => {
    console.log("🎉 ========== handlePaymentSuccess START ==========");
    console.log("🎉 Current order:", currentOrder);

    setIsProcessing(true);
    setLoading(true);

    try {
      console.log("🔍 Verifying payment for order:", currentOrder.order_id);
      // Verify payment (backend will automatically trigger dispense)
      await vendingAPI.verifyPayment(currentOrder.order_id, "SUCCESS");
      console.log("✅ Payment verified successfully");
      console.log("✅ Backend has automatically triggered dispense");

      console.log("🚀 Setting current screen to 'dispensing'...");
      setCurrentScreen("dispensing");
      console.log("🚀 Screen set to dispensing");

      toast.success("Pembayaran berhasil! Produk sedang dikeluarkan...");
      console.log("✅ Success toast shown");
    } catch (error: unknown) {
      console.error("❌ ========== ERROR IN handlePaymentSuccess ==========");
      console.error("❌ Error details:", error);
      console.error("❌ Error type:", typeof error);
      console.error("❌ Error constructor:", error?.constructor?.name);

      const errorMessage =
        (error as { response?: { data?: { error?: string } } })?.response?.data
          ?.error || "Gagal memverifikasi pembayaran";

      console.error("❌ Error message:", errorMessage);
      setError(errorMessage);
      toast.error(errorMessage);

      // IMPORTANT: Even if verification fails, still move to dispensing screen
      // The payment was already successful on Midtrans side
      console.log("⚠️ Despite error, payment was successful on Midtrans side");
      console.log("⚠️ Force moving to dispensing screen anyway...");
      setCurrentScreen("dispensing");
      console.log("⚠️ Screen forcefully set to dispensing");
    } finally {
      setIsProcessing(false);
      setLoading(false);
      console.log("🏁 ========== handlePaymentSuccess END ==========");
    }
  };

  const handleTimeout = () => {
    setError("Waktu pembayaran telah habis. Silakan coba lagi.");
    setPaymentToken(null); // Clear token
    resetTransaction();
    setCurrentScreen("home");
  };

  const handleBackToSummary = () => {
    setPaymentToken(null); // Clear token when going back
    setCurrentScreen("order-summary");
  };

  // Show payment method selection if no method is chosen
  if (!paymentMethod) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="max-w-2xl mx-auto">
          {/* Header */}
          <div className="flex items-center mb-6">
            <button
              onClick={handleBackToSummary}
              className="p-3 rounded-full bg-white border border-gray-100 text-orange-500 shadow-sm hover:shadow-md transition mr-4 hover:bg-orange-50"
            >
              <ArrowLeft className="h-5 w-5" />
            </button>
            <div>
              <div className="flex items-center gap-2 text-orange-600 text-xs font-bold uppercase tracking-widest mb-1">
                <Wallet className="h-4 w-4" /> Pembayaran
              </div>
              <h1 className="text-2xl font-black text-amber-900 tracking-tight">
                Pilih Metode Pembayaran
              </h1>
            </div>
          </div>

          {/* Order Summary */}
          <div className="mb-6 bg-white rounded-[2rem] shadow-xl shadow-amber-100/20 border border-amber-100 p-6">
            <div className="bg-amber-50 rounded-2xl p-4 border border-amber-50">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-bold text-lg text-gray-900 flex items-center gap-2">
                    <ShoppingBag className="h-5 w-5 text-orange-500" />
                    {selectedProduct.name}
                  </h3>
                  <p className="text-gray-600">
                    Jumlah: {currentOrder.quantity}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-3xl font-black text-orange-600">
                    Rp {currentOrder.total_amount.toLocaleString("id-ID")}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Payment Methods */}
          <div className="space-y-4">
            <div
              className="cursor-pointer hover:border-orange-400 hover:shadow-xl transition-all duration-200 border border-transparent bg-white rounded-3xl shadow-lg shadow-gray-100 p-6 hover:bg-orange-50 group"
              onClick={async () => {
                try {
                  // Update payment method in backend
                  const response = await vendingAPI.updatePaymentMethod(
                    currentOrder.order_id,
                    "midtrans"
                  );
                  // Verify response has payment_token
                  if (response.payment_token) {
                      setPaymentToken(response.payment_token);
                      console.log("✅ Token received from backend:", response.payment_token);
                  }
                  setPaymentMethod("midtrans");
                } catch (error) {
                  console.error("Failed to update payment method:", error);
                  toast.error("Gagal memilih metode pembayaran");
                }
              }}
            >
              <div className="flex items-center space-x-4">
                <div className="rounded-xl text-white overflow-hidden shadow-sm">
                  {/* <CreditCard className="h-6 w-6" /> */}
                  <Image
                    src="/bank-logo.jpg"
                    alt="Bank Logo"
                    width={56}
                    height={56}
                    className="object-cover"
                  />
                </div>
                <div className="flex-1">
                  <h3 className="font-bold text-lg text-gray-900 group-hover:text-orange-700 transition-colors">
                    Midtrans Payment
                  </h3>
                  <p className="text-gray-500 text-sm">
                    Visa, Mastercard, Bank Transfer, E-Wallet, QRIS
                  </p>
                </div>
                <div className="text-orange-400 font-black text-2xl group-hover:translate-x-1 transition-transform">→</div>
              </div>
            </div>


          </div>
        </div>
      </div>
    );
  }

  // Show Midtrans payment
  if (paymentMethod === "midtrans") {
    return (
      <div className="min-h-screen bg-amber-50/30 p-6">
        <div className="max-w-2xl mx-auto">
          <div className="flex items-center mb-6">
            <button
              onClick={() => {
                setPaymentMethod(null);
                setPaymentToken(null); // Clear token when going back
              }}
              className="p-3 rounded-full bg-white border border-gray-100 text-orange-500 shadow-sm hover:shadow-md transition mr-4 hover:bg-orange-50"
            >
              <ArrowLeft className="h-5 w-5" />
            </button>
            <div>
              <div className="flex items-center gap-2 text-orange-600 text-xs font-bold uppercase tracking-widest mb-1">
                <ShieldCheck className="h-4 w-4" /> Midtrans
              </div>
              <h1 className="text-2xl font-black text-amber-900 tracking-tight">
                Pembayaran Midtrans
              </h1>
            </div>
          </div>

          <div className="border border-amber-100 bg-white rounded-[2rem] shadow-xl shadow-amber-100/20 p-8 text-center">
            <div className="bg-orange-500 w-20 h-20 rounded-2xl flex items-center justify-center mx-auto mb-6 text-white shadow-lg shadow-orange-200">
              <CreditCard className="h-10 w-10" />
            </div>

            <h2 className="text-2xl font-black mb-4 text-gray-900">
              Bayar dengan Midtrans
            </h2>
            <p className="text-gray-500 mb-8 max-w-sm mx-auto">
              Klik tombol di bawah untuk membuka halaman pembayaran yang aman
            </p>

            <div className="bg-amber-50 rounded-2xl p-6 mb-8 border border-amber-100">
              <div className="flex justify-between items-center">
                <span className="font-bold text-gray-900">
                  {selectedProduct.name}
                </span>
                <span className="font-black text-orange-600 text-2xl">
                  Rp {currentOrder.total_amount.toLocaleString("id-ID")}
                </span>
              </div>
            </div>

            <Button
              onClick={handleMidtransPayment}
              disabled={isProcessing}
              variant="primary"
              fullWidth
              size="lg"
              className="mb-6 bg-orange-500 hover:bg-orange-600 border-none shadow-lg shadow-orange-200 py-4 h-auto text-lg rounded-2xl"
            >
              {isProcessing ? "Memproses..." : "💳 Bayar Sekarang"}
            </Button>

            <p className="text-xs text-gray-400 font-medium">
              🔒 Powered by Midtrans - Payment Gateway Terpercaya
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Show QRIS payment (existing implementation)
  return (
    <div className="min-h-screen bg-amber-50/30 p-6">
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center mb-6">
          <button
            onClick={() => {
              setPaymentMethod(null);
              setPaymentToken(null); // Clear token when going back
            }}
            className="p-3 rounded-full bg-white border border-gray-100 text-orange-500 shadow-sm hover:shadow-md transition mr-4 hover:bg-orange-50"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div>
            <div className="flex items-center gap-2 text-orange-600 text-xs font-bold uppercase tracking-widest mb-1">
              <QrCode className="h-4 w-4" /> QRIS
            </div>
            <h1 className="text-2xl font-black text-amber-900">
              Pembayaran QRIS
            </h1>
          </div>
        </div>

        <PaymentQR
          order={currentOrder}
          onPaymentSuccess={handlePaymentSuccess}
          onPaymentTimeout={handleTimeout}
          onClose={handleBackToSummary}
        />
      </div>
    </div>
  );
};

export default PaymentScreen;
